
version: '3.9'

services:
  app:
    container_name: staycool-pos
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8878:8878"
    # Env variables will be read from the .env file in the same directory
    env_file:
      - .env

